<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.example</groupId>
	<artifactId>test</artifactId>
	<name>test</name>
	<version>1.0.0</version>
	<packaging>jar</packaging>
	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<testSourceDirectory>test</testSourceDirectory>
		<outputDirectory>../out/production/test</outputDirectory>
		<testOutputDirectory>../out/test/test</testOutputDirectory>
		<directory>../out/build/test</directory>
		<resources>
			<resource>
				<directory>res</directory>
			</resource>
		</resources>
		<plugins>

			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<proc>none</proc>
				</configuration>
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<skipMain>true</skipMain>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addClasspath>true</addClasspath>
							<mainClass>org.example.test.model.Main</mainClass>
							<packageName>org.example</packageName>
							<classpathPrefix>dependency/</classpathPrefix>
						</manifest>
						<manifestSections>
							<manifestSection>
								<name>parameters</name>
								<manifestEntries>
									<home_name>home</home_name>
									<home_description>no description</home_description>
									<home_required>true</home_required>
									<home_defaultValue></home_defaultValue>
									<backup_directory_name>backup_directory</backup_directory_name>
									<backup_directory_description>no description</backup_directory_description>
									<backup_directory_required>true</backup_directory_required>
									<backup_directory_defaultValue></backup_directory_defaultValue>
									<datalake_directory_name>datalake_directory</datalake_directory_name>
									<datalake_directory_description>no description</datalake_directory_description>
									<datalake_directory_required>true</datalake_directory_required>
									<datalake_directory_defaultValue></datalake_directory_defaultValue>
									<broker_port_name>broker_port</broker_port_name>
									<broker_port_description>no description</broker_port_description>
									<broker_port_required>true</broker_port_required>
									<broker_port_defaultValue></broker_port_defaultValue>
									<broker_secondary_port_name>broker_secondary_port</broker_secondary_port_name>
									<broker_secondary_port_description>no description
									</broker_secondary_port_description>
									<broker_secondary_port_required>true</broker_secondary_port_required>
									<broker_secondary_port_defaultValue></broker_secondary_port_defaultValue>
									<keystore_password_name>keystore_password</keystore_password_name>
									<keystore_password_description>no description</keystore_password_description>
									<keystore_password_required>true</keystore_password_required>
									<keystore_password_defaultValue></keystore_password_defaultValue>
									<keystore_path_name>keystore_path</keystore_path_name>
									<keystore_path_description>no description</keystore_path_description>
									<keystore_path_required>true</keystore_path_required>
									<keystore_path_defaultValue></keystore_path_defaultValue>
									<truststore_password_name>truststore_password</truststore_password_name>
									<truststore_password_description>no description</truststore_password_description>
									<truststore_password_required>true</truststore_password_required>
									<truststore_password_defaultValue></truststore_password_defaultValue>
									<truststore_path_name>truststore_path</truststore_path_name>
									<truststore_path_description>no description</truststore_path_description>
									<truststore_path_required>true</truststore_path_required>
									<truststore_path_defaultValue></truststore_path_defaultValue>
								</manifestEntries>
							</manifestSection>
						</manifestSections>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.6.1</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<useBaseVersion>false</useBaseVersion>
							<includeScope>runtime</includeScope>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>gen</source>
								<source>src</source>
							</sources>
						</configuration>
					</execution>
					<execution>
						<id>add-test-source</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>test</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>intino-maven</id>
			<url>https://artifactory.intino.io/artifactory/releases</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>intino-maven-snapshot</id>
			<url>https://artifactory.intino.io/artifactory/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>systems.intino.eventsourcing</groupId>
			<artifactId>datahub</artifactId>
			<scope>compile</scope>
			<version>13.1.0</version>
		</dependency>
		<dependency>
			<groupId>systems.intino.eventsourcing</groupId>
			<artifactId>jms</artifactId>
			<scope>compile</scope>
			<version>2.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-client</artifactId>
			<scope>compile</scope>
			<version>6.2.7</version>
		</dependency>
		<dependency>
			<groupId>systems.intino.eventsourcing</groupId>
			<artifactId>datahub-terminal</artifactId>
			<scope>compile</scope>
			<version>6.2.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
			<version>4.13.2</version>
		</dependency>
	</dependencies>
</project>
