package systems.intino.eventsourcing.datahubbuilder.codegeneration.datamarts;

import io.intino.itrules.template.Rule;
import io.intino.itrules.template.Template;

import java.util.ArrayList;
import java.util.List;

import static io.intino.itrules.template.condition.predicates.Predicates.*;
import static io.intino.itrules.template.outputs.Outputs.*;

public class DatamartTemplate extends Template {

	public List<Rule> ruleSet() {
		List<Rule> rules = new ArrayList<>();
		rules.add(rule().condition(allTypes("datamart")).output(literal("package ")).output(placeholder("package")).output(literal(";\n\nimport systems.intino.eventsourcing.datahubterminal.Connector;\nimport systems.intino.eventsourcing.datahubterminal.datamart.ConnectionConfig;\nimport systems.intino.eventsourcing.datahubterminal.datamart.SubjectListener;\nimport systems.intino.datamarts.subjectstore.model.Subject;\n\nimport java.util.ArrayList;\nimport java.util.stream.Stream;\n\nimport ")).output(placeholder("ontologypackage")).output(literal(".*;\n\nimport static java.util.Objects.requireNonNull;\n\npublic class ")).output(placeholder("name", "FirstUpperCase")).output(literal("Datamart {\n\tprivate final systems.intino.eventsourcing.datahubterminal.datamart.Datamart core;\n\n\tpublic ")).output(placeholder("name", "FirstUpperCase")).output(literal("Datamart(Connector connector, ConnectionConfig connectionConfig) {\n\t\tthis.core = new systems.intino.eventsourcing.datahubterminal.datamart.Datamart(\"")).output(placeholder("name")).output(literal("\", connector, connectionConfig);\n\t}\n\n\tpublic ")).output(placeholder("name", "FirstUpperCase")).output(literal("Datamart init(String datamartSourceSelector) {\n\t\tthis.core$().init(datamartSourceSelector);\n\t\treturn this;\n\t}\n\n\tpublic systems.intino.eventsourcing.datahubterminal.datamart.Datamart core$() {\n\t\treturn core;\n\t}\n\n\tpublic void addSubjectListener(String type, SubjectListener listener) {\n\t\tif (listener == null) throw new NullPointerException(\"SubjectListener cannot be null\");\n\t\tcore$().addListener(type, listener);\n\t}\n\n\t")).output(expression().output(placeholder("subject", "getter").multiple("\n\n"))).output(literal("\n\n\t")).output(expression().output(placeholder("indicator", "getter").multiple("\n\n"))).output(literal("\n\n}")));
		rules.add(rule().condition(all(allTypes("abstract"), trigger("getter"))).output(literal("public ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("(String id) {\n\tif (id == null) return null;\n\tSubject node = core.getSubject(new String[]{")).output(placeholder("descendant", "quoted").multiple(", ")).output(literal("}, id);\n\tif (node == null) return null;\n\treturn new ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("(node, core);\n}\n\npublic Stream<")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("> ")).output(placeholder("name", "Plural", "firstLowerCase")).output(literal("() {\n\treturn core.subjects(new String[]{")).output(placeholder("descendant", "quoted").multiple(",")).output(literal("}).map(s -> new ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("(s, core));\n}")));
		rules.add(rule().condition(all(all(allTypes("superclass"), not(allTypes("abstract"))), trigger("getter"))).output(literal("public ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("(String id) {\n\treturn id == null ? null : new ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("(core.getSubject(\"")).output(placeholder("name")).output(literal("\", id), core);\n}\n\npublic Stream<")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("> ")).output(placeholder("name", "Plural", "firstLowerCase")).output(literal("() {\n\treturn core.subjects(\"")).output(placeholder("name")).output(literal("\").map(s -> new ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("(s));\n}")));
		rules.add(rule().condition(trigger("getter")).output(literal("public ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("(String id) {\n\treturn id == null ? null : new ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("(core.getSubject(\"")).output(placeholder("name")).output(literal("\", id), core);\n}\n\npublic Stream<")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("> ")).output(placeholder("name", "Plural", "firstLowerCase")).output(literal("() {\n\treturn core.subjects(\"")).output(placeholder("name")).output(literal("\").map(s -> new ")).output(placeholder("package")).output(literal(".subjects.")).output(placeholder("name", "FirstUpperCase")).output(literal("(s, core));\n}")));
		return rules;
	}

	public String render(Object object) {
		return new io.intino.itrules.Engine(this).render(object);
	}

	public String render(Object object, java.util.Map<String, io.intino.itrules.Formatter> formatters) {
		return new io.intino.itrules.Engine(this).addAll(formatters).render(object);
	}
}