package systems.intino.eventsourcing.datahubbuilder.codegeneration.datamarts;

import io.intino.itrules.template.Rule;
import io.intino.itrules.template.Template;

import java.util.ArrayList;
import java.util.List;

import static io.intino.itrules.template.condition.predicates.Predicates.*;
import static io.intino.itrules.template.outputs.Outputs.*;

public class SubjectTemplate extends Template {

	public List<Rule> ruleSet() {
		List<Rule> rules = new ArrayList<>();
		rules.add(rule().condition(allTypes("subject", "root")).output(literal("package ")).output(placeholder("package")).output(literal(".subjects;\n\nimport java.time.*;\nimport java.util.*;\nimport java.util.stream.*;\nimport systems.intino.datamarts.subjectstore.model.Subject;\n\npublic class ")).output(placeholder("name", "FirstUpperCase")).output(literal(" ")).output(expression().output(literal("extends ")).output(placeholder("parent")).output(literal(" ")).next(expression().output(literal("extends systems.intino.eventsourcing.datahubterminal.datamart.SubjectWrapper ")))).output(literal("{\n\t")).output(expression().output(placeholder("attribute", "wordDeclaration").multiple("\n"))).output(literal("\n\n\tpublic ")).output(placeholder("abstract")).output(placeholder("name", "FirstUpperCase")).output(literal("(Subject core, systems.intino.eventsourcing.datahubterminal.datamart.Datamart datamart) {\n\t\tsuper(core, datamart);\n\t}\n\n\t")).output(expression().output(placeholder("attribute", "getter").multiple("\n\n"))).output(literal("\n\n\t")).output(expression().output(placeholder("expression", "expressionDeclaration").multiple("\n\n"))).output(literal("\n\n\t")).output(expression().output(placeholder("struct", "getter").multiple("\n\n"))).output(literal("\n\n\t")).output(expression().output(placeholder("struct", "class").multiple("\n\n"))).output(literal("\n}")));
		rules.add(rule().condition(all(allTypes("struct"), trigger("class"))).output(literal("public class ")).output(placeholder("name", "firstUpperCase")).output(literal(" {\n\tprivate final String prefix;\n\n\tpublic ")).output(placeholder("name", "FirstUpperCase")).output(literal("(String prefix) {\n\t\tthis.prefix = prefix;\n\t}\n\n\t")).output(expression().output(placeholder("attribute", "getter").multiple("\n\n"))).output(literal("\n\n\t")).output(expression().output(placeholder("struct", "getter").multiple("\n\n"))).output(literal("\n\n\t")).output(expression().output(placeholder("struct", "class").multiple("\n\n"))).output(literal("\n}")));
		rules.add(rule().condition(trigger("constructor")).output(literal("String prefix;\n\n")));
		rules.add(rule().condition(trigger("super")).output(literal("super(index)")));
		rules.add(rule().condition(all(allTypes("struct", "multiple"), trigger("getter"))).output(literal("public java.util.stream.Stream<")).output(placeholder("name", "firstUpperCase")).output(literal("> ")).output(placeholder("name", "firstLowerCase", "Plural")).output(literal("() {\n\tIterator<")).output(placeholder("name", "firstUpperCase")).output(literal("> iterator = new Iterator<>() {\n\t\tprivate int next = 0;\n\t\tprivate String value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" ")).next(expression().output(literal("\"")).output(placeholder("name", "firstUpperCase")).output(literal(".\" + ")))).output(literal("next + \".\");\n\n\t\t@Override\n\t\tpublic boolean hasNext() {\n\t\t\treturn value != null;\n\t\t}\n\n\t\t@Override\n\t\tpublic ")).output(placeholder("name", "firstUpperCase")).output(literal(" next() {\n\t\t\tif (value == null) return null;\n\t\t\tvar currentValue = new ")).output(placeholder("name", "firstUpperCase")).output(literal("(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" ")).next(expression().output(literal("\"")).output(placeholder("name", "firstUpperCase")).output(literal(".\" + ")))).output(literal("next + \".\");\n\t\t\tthis.next++;\n\t\t\tthis.value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" ")).next(expression().output(literal("\"")).output(placeholder("name", "firstUpperCase")).output(literal(".\" + ")))).output(literal("next + \".\");\n\t\t\treturn currentValue;\n\t\t}\n\t};\n\treturn StreamSupport.stream(Spliterators.spliteratorUnknownSize(iterator, Spliterator.ORDERED), false);\n}")));
		rules.add(rule().condition(all(allTypes("struct"), trigger("getter"))).output(literal("public ")).output(placeholder("name", "firstUpperCase")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn new ")).output(placeholder("name", "firstUpperCase")).output(literal("(")).output(expression().output(placeholder("isStruct", "prefix")).next(expression().output(literal("\"")).output(placeholder("name", "firstUpperCase")).output(literal("\" + \".\"")))).output(literal(");\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "text"), trigger("getter"))).output(literal("public java.util.List<String> ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\tString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n\treturn value == null ? java.util.Collections.emptyList() : java.util.List.of(value.split(\"\\0\"));\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "word"), trigger("getter"))).output(literal("public java.util.List<")).output(placeholder("name", "FirstUpperCase")).output(literal("> ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\tString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n\treturn value == null ? java.util.Collections.emptyList() : java.util.Arrays.stream(value.split(\"\\0\")).map(v -> ")).output(placeholder("name", "FirstUpperCase")).output(literal(".valueOf(v)).toList();\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "real"), trigger("getter"))).output(literal("public java.util.List<Double> ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\nString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\nreturn value == null ? java.util.Collections.emptyList() : java.util.Arrays.stream(value.split(\"\\0\")).map(v -> Double.parseDouble(v)).toList();\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "integer"), trigger("getter"))).output(literal("public java.util.List<Integer> ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\tString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n\treturn value == null ? java.util.Collections.emptyList() : java.util.Arrays.stream(value.split(\"\\0\")).map(v -> Integer.parseInt(v)).toList();\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "longInteger"), trigger("getter"))).output(literal("public java.util.List<Long> ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\tString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n\treturn value == null ? java.util.Collections.emptyList() : java.util.Arrays.stream(value.split(\"\\0\")).map(v -> Long.parseLong(v)).toList();\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "bool"), trigger("getter"))).output(literal("public Boolean ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\tString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n\treturn value == null ? java.util.Collections.emptyList() : java.util.Arrays.stream(value.split(\"\\0\")).map(v -> v.equals(\"0\")).toList();\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "multiple", "date"), trigger("getter"))).output(literal("public java.util.Date ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn new java.util.Date(current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").longValue());\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), any(allTypes("instant"), allTypes("dateTime"))), trigger("getter"))).output(literal("public Instant ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn java.time.Instant.ofEpochMilli(current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").longValue());\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "subject"), trigger("getter"))).output(literal("public ")).output(placeholder("targetType", "FirstUpperCase")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn new ")).output(placeholder("targetType", "FirstUpperCase")).output(literal("(datamart$().getSubject(current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\"), \"")).output(placeholder("targetType")).output(literal("\"), datamart());\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "text"), trigger("getter"))).output(literal("public ")).output(placeholder("type")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n}")));
		rules.add(rule().condition(all(allTypes("attribute", "word"), trigger("getter"))).output(literal("public ")).output(placeholder("name", "FirstUpperCase")).output(literal(" ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\tString value = current$().text(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\");\n\treturn value == null ? null : ")).output(placeholder("name", "FirstUpperCase")).output(literal(".valueOf(value);\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), allTypes("real")), trigger("getter"))).output(literal("public Double ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").doubleValue();\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), allTypes("integer")), trigger("getter"))).output(literal("public Integer ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").intValue();\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), allTypes("long")), trigger("getter"))).output(literal("public Long ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").longValue();\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), allTypes("boolean")), trigger("getter"))).output(literal("public Boolean ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn current$().number(\"")).output(placeholder("name")).output(literal(").intValue != 0;\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), allTypes("date")), trigger("getter"))).output(literal("public java.util.Date ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn new java.util.Date(current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").longValue());\n}")));
		rules.add(rule().condition(all(all(allTypes("attribute"), any(allTypes("instant"), allTypes("dateTime"))), trigger("getter"))).output(literal("public Instant ")).output(placeholder("name", "firstLowerCase")).output(literal("() {\n\treturn java.time.Instant.ofEpochMilli(current$().number(")).output(expression().output(placeholder("isStruct", "prefix")).output(literal(" "))).output(literal("\"")).output(placeholder("name")).output(literal("\").longValue());\n}")));
		rules.add(rule().condition(all(attribute("", "true"), trigger("isabstract"))).output(literal("abstract")));
		rules.add(rule().condition(all(allTypes("word"), trigger("worddeclaration"))).output(literal("public enum ")).output(placeholder("name", "FirstUpperCase")).output(literal(" {\n\t")).output(placeholder("words").multiple(", ")).output(literal("\n}")));
		rules.add(rule().condition(trigger("prefix")).output(literal("prefix +")));
		rules.add(rule().condition(trigger("worddeclaration")));
		rules.add(rule().condition(trigger("empty")).output(literal(";")));
		return rules;
	}

	public String render(Object object) {
		return new io.intino.itrules.Engine(this).render(object);
	}

	public String render(Object object, java.util.Map<String, io.intino.itrules.Formatter> formatters) {
		return new io.intino.itrules.Engine(this).addAll(formatters).render(object);
	}
}