<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>systems.intino.eventsourcing</groupId>
	<artifactId>datahub</artifactId>
	<name>datahub</name>
	<version>13.1.1</version>
	<packaging>jar</packaging>
	<description>DataHub is a software platform that facilitates the creation, management, and distribution of events in event-driven systems. Using a domain-specific language (DSL), DataHub allows users to tailor their architecture to meet specific business needs, enhancing the integration and operability of real-time data systems</description>
	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<testSourceDirectory>test</testSourceDirectory>
		<outputDirectory>../out/production/datahub</outputDirectory>
		<testOutputDirectory>../out/test/datahub</testOutputDirectory>
		<directory>../out/build/datahub</directory>
		<resources>
			<resource><directory>res</directory></resource>
		</resources>
		<plugins>

			<plugin>
				  <artifactId>maven-clean-plugin</artifactId>
				  <version>3.0.0</version>
				  <configuration>
					<skip>true</skip>
				  </configuration>
				</plugin>
			 <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<skipMain>true</skipMain>
						</configuration>
					</execution>
				</executions>
			</plugin><plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<finalName>ness</finalName>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addClasspath>true</addClasspath>
							<mainClass>systems.intino.eventsourcing.datahub.box.Main</mainClass>
							<packageName>systems.intino.eventsourcing</packageName>
							<classpathPrefix>lib/</classpathPrefix>
						</manifest>
						<manifestEntries>
							<description>DataHub is a software platform that facilitates the creation, management, and distribution of events in event-driven systems. Using a domain-specific language (DSL), DataHub allows users to tailor their architecture to meet specific business needs, enhancing the integration and operability of real-time data systems</description>
						</manifestEntries>
						<manifestSections>
							<manifestSection>
								<name>parameters</name>
								<manifestEntries>
								  <home_name>home</home_name>
								  <home_description>no description</home_description>
								  <home_required>true</home_required>
								  <home_defaultValue></home_defaultValue>
								  <broker_port_name>broker_port</broker_port_name>
								  <broker_port_description>no description</broker_port_description>
								  <broker_port_required>true</broker_port_required>
								  <broker_port_defaultValue></broker_port_defaultValue>
								  <broker_secondary_port_name>broker_secondary_port</broker_secondary_port_name>
								  <broker_secondary_port_description>no description</broker_secondary_port_description>
								  <broker_secondary_port_required>true</broker_secondary_port_required>
								  <broker_secondary_port_defaultValue></broker_secondary_port_defaultValue>
								  <backup_directory_name>backup_directory</backup_directory_name>
								  <backup_directory_description>no description</backup_directory_description>
								  <backup_directory_required>true</backup_directory_required>
								  <backup_directory_defaultValue></backup_directory_defaultValue>
								  <keystore_path_name>keystore_path</keystore_path_name>
								  <keystore_path_description>no description</keystore_path_description>
								  <keystore_path_required>true</keystore_path_required>
								  <keystore_path_defaultValue></keystore_path_defaultValue>
								  <keystore_password_name>keystore_password</keystore_password_name>
								  <keystore_password_description>no description</keystore_password_description>
								  <keystore_password_required>true</keystore_password_required>
								  <keystore_password_defaultValue></keystore_password_defaultValue>
								  <truststore_path_name>truststore_path</truststore_path_name>
								  <truststore_path_description>no description</truststore_path_description>
								  <truststore_path_required>true</truststore_path_required>
								  <truststore_path_defaultValue></truststore_path_defaultValue>
								  <truststore_password_name>truststore_password</truststore_password_name>
								  <truststore_password_description>no description</truststore_password_description>
								  <truststore_password_required>true</truststore_password_required>
								  <truststore_password_defaultValue></truststore_password_defaultValue>
								</manifestEntries>
							</manifestSection>
						</manifestSections>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.6.1</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
							<useBaseVersion>false</useBaseVersion>
							<includeScope>runtime</includeScope>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>add-source</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>gen</source>
								<source>src</source>

							</sources>
						</configuration>
					</execution>
					<execution>
						<id>add-test-source</id>
						<phase>generate-test-sources</phase>
						<goals>
							<goal>add-test-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>test</source>
								<source>test-gen</source>

							</sources>
						</configuration>
						</execution>
				</executions>
			</plugin>
			 <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.3.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>intino-maven</id>
			<url>https://artifactory.intino.io/artifactory/releases</url>
			<snapshots><enabled>false</enabled></snapshots>
		</repository>
		<repository>
			<id>intino-maven-snapshot</id>
			<url>https://artifactory.intino.io/artifactory/snapshots</url>
			<snapshots><enabled>true</enabled></snapshots>
		</repository>
	</repositories>

	<distributionManagement>
		<repository>
			<id>intino-maven</id>
			<name>intino-maven</name>
			<url>https://artifactory.intino.io/artifactory/release-libraries</url>
		</repository>
	</distributionManagement>

	<dependencies>
		<dependency>
			<groupId>io.intino.magritte</groupId>
			<artifactId>framework</artifactId>
			<scope>compile</scope>
			<version>5.2.1</version>
		</dependency>
		<dependency>
			<groupId>systems.intino.eventsourcing</groupId>
			<artifactId>sealing</artifactId>
			<scope>compile</scope>
			<version>7.1.0</version>
		</dependency>
		<dependency>
			<groupId>systems.intino.eventsourcing</groupId>
			<artifactId>jms</artifactId>
			<scope>compile</scope>
			<version>2.1.1</version>
		</dependency>
		<dependency>
			<groupId>systems.intino.datamarts</groupId>
			<artifactId>subject-store</artifactId>
			<scope>compile</scope>
			<version>2.0.4</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>json</artifactId>
			<scope>compile</scope>
			<version>1.2.3</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>core-framework</artifactId>
			<scope>compile</scope>
			<version>2.2.2</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>jmx</artifactId>
			<scope>compile</scope>
			<version>1.0.8</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>primitives</artifactId>
			<scope>compile</scope>
			<version>1.1.6</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>exceptions</artifactId>
			<scope>compile</scope>
			<version>2.1.2</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>zip</artifactId>
			<scope>compile</scope>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>logger4j</artifactId>
			<scope>compile</scope>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>io.intino.alexandria</groupId>
			<artifactId>scheduler-framework</artifactId>
			<scope>compile</scope>
			<version>1.2.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<scope>compile</scope>
			<version>2.22.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-broker</artifactId>
			<scope>compile</scope>
			<version>6.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-mqtt</artifactId>
			<scope>compile</scope>
			<version>6.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-kahadb-store</artifactId>
			<scope>compile</scope>
			<version>6.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-jaas</artifactId>
			<scope>compile</scope>
			<version>6.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-runtime-config</artifactId>
			<scope>compile</scope>
			<version>6.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.xerial</groupId>
			<artifactId>sqlite-jdbc</artifactId>
			<scope>compile</scope>
			<version>3.53.4.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
			<version>4.13.2</version>
		</dependency>
	</dependencies>
</project>