package io.intino.ness.datahubterminalplugin.renders.lookups;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class LookupTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
			rule().condition((type("root"))).output(literal("package ")).output(mark("package", "ValidPackage")).output(literal(";\n\n")).output(mark("lookup")),
			rule().condition((allTypes("lookup","resource"))).output(literal("import java.util.ArrayList;\nimport java.util.List;\nimport java.util.function.Predicate;\nimport java.util.stream.Collectors;\n\npublic class ")).output(mark("name", "FirstUpperCase")).output(literal(" {\n\tpublic static final Entry NA = new Entry(")).output(mark("column", "defaultValue").multiple(", ")).output(literal(");\n\tprivate static final java.util.Map<Short, Entry> entries;\n\tprivate static final java.util.Map<String, Entry> entriesByName;\n\n\tstatic {\n\t\tentries = new java.util.HashMap<>();\n\t\tentriesByName = new java.util.HashMap<>();\n\t\ttry (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(")).output(mark("name", "FirstUpperCase")).output(literal(".class.getResourceAsStream(\"/")).output(mark("resource")).output(literal("\")))) {\n\t\t\treader.lines().map(l -> l.split(\"\\t\", -1)).\n\t\t\tmap(l -> new Entry(")).output(mark("column", "constructor").multiple(", ")).output(literal(")).\n\t\t\tforEach(e -> {entries.put((short) e.index, e); entriesByName.put(e.name, e);});\n\t\t} catch (java.io.IOException e) {\n\t\t\tio.intino.alexandria.logger.Logger.error(e);\n\t\t}\n\t}\n\n\tpublic static List<Entry> entries() {\n\t\treturn new ArrayList<>(entries.values());\n\t}\n\n\tpublic static List<Entry> entries(Predicate<Entry> filter) {\n\t\treturn entries.values().stream().filter(filter).collect(Collectors.toList());\n\t}\n\n\tpublic static Entry entry(int index) {\n\t\treturn entries.getOrDefault((short)index, NA);\n\t}\n\n\tpublic static Entry entry(String name) {\n\t\treturn entriesByName.getOrDefault(name, NA);\n\t}\n\n\tpublic static class Entry {\n\t\t")).output(mark("column", "declaration").multiple("\n")).output(literal("\n\n\t\tEntry(")).output(mark("column", "parameter").multiple(", ")).output(literal(") {\n\t\t\t")).output(mark("column", "assign").multiple("\n")).output(literal("\n\t\t}\n\n\t\tpublic boolean equals(Entry entry) {\n\t\t\treturn this.index == entry.index;\n\t\t}\n\t}\n}")),
			rule().condition((allTypes("lookup","enumerate"))).output(literal("import java.util.ArrayList;\nimport java.util.List;\nimport java.util.function.Predicate;\nimport java.util.stream.Collectors;\n\npublic class ")).output(mark("name", "firstUpperCase")).output(literal(" {\n\tprivate static final java.util.Map<Short, Entry> entries;\n\tprivate static final java.util.Map<String, Entry> entriesByName;\n\tpublic static final Entry NA = new Entry((short) 0, \"NA\");\n\t")).output(mark("entry", "field").multiple("\n")).output(literal("\n\tstatic {\n\t\tentries = new java.util.HashMap<>();\n\t\tentriesByName = new java.util.HashMap<>();\n\t\t")).output(mark("entry", "put").multiple("\n")).output(literal("\n\t}\n\n\tpublic static List<Entry> entries() {\n\t\treturn new ArrayList<>(entries.values());\n\t}\n\n\tpublic static List<Entry> entries(Predicate<Entry> filter) {\n\t\treturn entries.values().stream().filter(filter).collect(Collectors.toList());\n\t}\n\n\tpublic static Entry entry(int index) {\n\t\treturn entries.getOrDefault((short)index, NA);\n\t}\n\n\tpublic static Entry entry(String name) {\n\t\treturn entriesByName.getOrDefault(name, NA);\n\t}\n\n\tpublic static class Entry {\n\t\tpublic final short index;\n\t\tpublic final String name;\n\t\tpublic final String label;\n\n\t\tEntry(short index, String name) {\n\t\t\tthis(index, name, name);\n\t\t}\n\n\t\tEntry(short index, String name, String label) {\n\t\t\tthis.index = index;\n\t\t\tthis.name = name;\n\t\t\tthis.label = label;\n\t\t}\n\n\t\tpublic boolean equals(Entry entry) {\n\t\t\treturn this.index == entry.index;\n\t\t}\n\t}\n}")),
			rule().condition((trigger("declaration"))).output(literal("public final ")).output(mark("type")).output(literal(" ")).output(mark("name", "firstLowerCase")).output(literal(";")),
			rule().condition((trigger("parameter"))).output(mark("type")).output(literal(" ")).output(mark("name", "firstLowerCase")),
			rule().condition((anyTypes("string","text")), (trigger("constructor"))).output(literal("l.length > ")).output(mark("index")).output(literal(" ? l[")).output(mark("index")).output(literal("] : \"NA\"")),
			rule().condition((type("integer")), (trigger("constructor"))).output(literal("l.length > ")).output(mark("index")).output(literal(" ? Integer.parseInt(l[")).output(mark("index")).output(literal("]) : -1")),
			rule().condition((type("real")), (trigger("constructor"))).output(literal("l.length > ")).output(mark("index")).output(literal(" ? Double.parseDouble(l[")).output(mark("index")).output(literal("]) : Double.NaN")),
			rule().condition((anyTypes("longInteger","long")), (trigger("constructor"))).output(literal("l.length > ")).output(mark("index")).output(literal(" ? Long.parseLong(l[")).output(mark("index")).output(literal("]) : -1L")),
			rule().condition((anyTypes("boolean","bool")), (trigger("constructor"))).output(literal("l.length > ")).output(mark("index")).output(literal(" ? Boolean.parseBoolean(l[")).output(mark("index")).output(literal("]) : false")),
			rule().condition((anyTypes("string","text")), (trigger("defaultvalue"))).output(literal("\"NA\"")),
			rule().condition((type("integer")), (trigger("defaultvalue"))).output(literal("0")),
			rule().condition((type("real")), (trigger("defaultvalue"))).output(literal("0.")),
			rule().condition((anyTypes("longInteger","long")), (trigger("defaultvalue"))).output(literal("0L")),
			rule().condition((anyTypes("boolean","bool")), (trigger("defaultvalue"))).output(literal("false")),
			rule().condition((trigger("assign"))).output(literal("this.")).output(mark("name", "firstLowerCase")).output(literal(" = ")).output(mark("name", "firstLowerCase")).output(literal(";")),
			rule().condition((trigger("put"))).output(literal("entries.put((short) ")).output(mark("index")).output(literal(", ")).output(mark("name", "FirstUpperCase")).output(literal(");\nentriesByName.put(\"")).output(mark("name")).output(literal("\", ")).output(mark("name", "FirstUpperCase")).output(literal(");")),
			rule().condition((trigger("field"))).output(literal("public static final Entry ")).output(mark("name", "FirstUpperCase")).output(literal(" = new Entry((short) ")).output(mark("index")).output(literal(", \"")).output(mark("name")).output(literal("\"")).output(expression().output(literal(", \"")).output(mark("label")).output(literal("\""))).output(literal(");"))
		);
	}
}